module.exports =
{
  "1": "About life inside the game and basic character development.",
  "2": "How to complete your novicehood and benefit greatly from the experience.",
  "3": "An overview of the different areas of the world.",
  "4": "Moving around, basic actions and learning skills within Avalon.",
  "5": "Talking to others in the game, through the bulletin board, and through the written word.",
  "6": "Information on other parts of a character, from questing for gold to changing your alignment.",
  "7": "How to guide your character through basic combat maneuvers.",
  "8": "Ensuring your character's physical and mental well-being as you progress.",
  "9": "Information you should learn as to occurences unique within the Avalon system.",
  "10": "Dealing with inanimate objects and sentient mobiles throughout the world.",
  "11": "Learning about the importance of Guilds and duties within the land.",
  "12": "Discover a wealth of information on the various parts of the mainland continent.",
  "13": "Information about some of the major towns and villages scattered throughout the land.",
  "14": "One day you must choose a binding and specialist profession, that will steer the rest of your mortal life.",
  "15": "Information about many of the guilds around the land. Much of your guild choice will be based on what is written herein.",
  "16": "Along with your basic skillset, you will be given the ability to further your development in several more specialist fields.",
  "17": "The individual skillsets and the relative abilities of each.",
  "18": "Information about cities and the various posts your character may hold, from Justice to the sole city Prince.",
  "19": "General command lists specific to Government officials and their aides.",
  "20": "Commands specific to each individual government post.",
  "21": "War inside of the game, between guilds, cities and allied forces - all related information about the strain on resources is here.",
  "22": "The Gods of Avalon, what they stand for and why you should consider joining an order.",
  "23": "Important events in the land, from times past.",
  "24": "Recent times in the land, and events that have occurred over the last few months.",
  "25": "Non-character related information is here, from the Mentor system to various important quests that occur every few months.",
  "26": "Various lists such as those characters who hold various important posts, nutritional information, and the divine gems available.",
  "27": "The various command lists concerning almost every general situation.",
  "28": "The various situations specific to Avalon, from quizzes to modem access.",
  "29": "Other information not covered in the general help."
}